# Generated by Django 4.1.5 on 2023-01-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='product_img')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('offer', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='offer',
            field=models.IntegerField(),
        ),
    ]
